name: Deploy to Oracle Cloud

on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
    with:
      host: ${{ secrets.158.180.34.116 }}
      username: ubuntu
      key: ${{ secrets.10.0.0.44 }}
      script: |
        cd /var/www/myapp
        sudo git pull origin main
        sudo systemctl reload nginx
